### ISSUE TITLE
Generated packages not being generated

### ISSUE THREAD

**Issue by AndreiTuta** [DivitGitHub/spring-graphql-api#11]
> mvn install

[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< com.divitngoc:spring-graphql-api >------------------
[INFO] Building spring-graphql-api 1.0.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- jooq-codegen-maven:3.11.10:generate (default) @ spring-graphql-api ---
[INFO] Database                 : Inferring database org.jooq.meta.h2.H2Database from URL jdbc:h2:~/jooq
[INFO] No <inputCatalog/> was provided. Generating ALL available catalogs instead.
[INFO] License parameters       
[INFO] ----------------------------------------------------------
[INFO]   Thank you for using jOOQ and jOOQ's code generator
[INFO]                          
[INFO] Database parameters      
[INFO] ----------------------------------------------------------
[INFO]   dialect                : H2
[INFO]   URL                    : jdbc:h2:~/jooq
[INFO]   target dir             : /home/at/git/spring-graphql-api/spring-graphql-api/src/gen
[INFO]   target package         : com.divitngoc.generated
[INFO]   includes               : [artist|song]
[INFO]   excludes               : []
[INFO]   includeExcludeColumns  : false
[INFO] ----------------------------------------------------------
[INFO]                          
[INFO] JavaGenerator parameters 
[INFO] ----------------------------------------------------------
[INFO]   annotations (generated): true
[INFO]   annotations (JPA: any) : false
[INFO]   annotations (JPA: version): 
[INFO]   annotations (validation): false
[INFO]   comments               : true
[INFO]   comments on attributes : true
[INFO]   comments on catalogs   : true
[INFO]   comments on columns    : true
[INFO]   comments on keys       : true
[INFO]   comments on links      : true
[INFO]   comments on packages   : true
[INFO]   comments on parameters : true
[INFO]   comments on queues     : true
[INFO]   comments on routines   : true
[INFO]   comments on schemas    : true
[INFO]   comments on sequences  : true
[INFO]   comments on tables     : true
[INFO]   comments on udts       : true
[INFO]   daos                   : true
[INFO]   deprecated code        : false
[INFO]   global references (any): true
[INFO]   global references (catalogs): true
[INFO]   global references (keys): true
[INFO]   global references (links): true
[INFO]   global references (queues): true
[INFO]   global references (routines): true
[INFO]   global references (schemas): true
[INFO]   global references (sequences): true
[INFO]   global references (tables): true
[INFO]   global references (udts): true
[INFO]   indexes                : true
[INFO]   instance fields        : true
[INFO]   interfaces             : false
[INFO]   interfaces (immutable) : false
[INFO]   javadoc                : true
[INFO]   keys                   : true
[INFO]   links                  : true
[INFO]   pojos                  : true
[INFO]   pojos (immutable)      : false
[INFO]   queues                 : true
[INFO]   records                : true
[INFO]   routines               : true
[INFO]   sequences              : true
[INFO]   table-valued functions : true
[INFO]   tables                 : true
[INFO]   udts                   : true
[INFO]   relations              : true
[INFO] ----------------------------------------------------------
[INFO]                          
[INFO] Generation remarks       
[INFO] ----------------------------------------------------------
[INFO]                          
[INFO] ----------------------------------------------------------
[INFO] Generating catalogs      : Total: 1
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jooq.tools.reflect.Reflect (file:/home/at/.m2/repository/org/jooq/jooq/3.11.10/jooq-3.11.10.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class)
WARNING: Please consider reporting this to the maintainers of org.jooq.tools.reflect.Reflect
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] 
                                      
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@  @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@        @@@@@@@@@@
@@@@@@@@@@@@@@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@  @@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@        @@  @  @  @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@  @@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  Thank you for using jOOQ 3.11.9
                                      
[INFO] ARRAYs fetched           : 0 (0 included, 0 excluded)
[INFO] Enums fetched            : 0 (0 included, 0 excluded)
[INFO] Packages fetched         : 0 (0 included, 0 excluded)
[INFO] Routines fetched         : 0 (0 included, 0 excluded)
[INFO] Tables fetched           : 0 (0 included, 0 excluded)
[INFO] UDTs fetched             : 0 (0 included, 0 excluded)
[INFO] Excluding empty catalog  : 
[INFO] Removing excess files    
[INFO] 
[INFO] --- build-helper-maven-plugin:3.0.0:add-source (default) @ spring-graphql-api ---
[INFO] Source directory: /home/at/git/spring-graphql-api/spring-graphql-api/src/gen added.
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ spring-graphql-api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ spring-graphql-api ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ spring-graphql-api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ spring-graphql-api ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 7 source files to /home/at/git/spring-graphql-api/spring-graphql-api/target/test-classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/at/git/spring-graphql-api/spring-graphql-api/src/test/java/com/divitngoc/controller/MusicApiControllerTest.java:[21,44] package com.divitngoc.generated.tables.pojos does not exist
[ERROR] /home/at/git/spring-graphql-api/spring-graphql-api/src/test/java/com/divitngoc/graphql/ArtistResolverTest.java:[16,44] package com.divitngoc.generated.tables.pojos does not exist
[ERROR] /home/at/git/spring-graphql-api/spring-graphql-api/src/test/java/com/divitngoc/db/service/ArtistServiceTest.java:[18,44] package com.divitngoc.generated.tables.pojos does not exist
[ERROR] /home/at/git/spring-graphql-api/spring-graphql-api/src/test/java/com/divitngoc/db/service/SongServiceTest.java:[20,44] package com.divitngoc.generated.tables.pojos does not exist
[ERROR] /home/at/git/spring-graphql-api/spring-graphql-api/src/test/java/com/divitngoc/graphql/SongResolverTest.java:[15,44] package com.divitngoc.generated.tables.pojos does not exist
[INFO] 5 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.824 s
[INFO] Finished at: 2019-06-18T21:29:44+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:testCompile (default-testCompile) on project spring-graphql-api: Compilation failure: Compilation failure: 
[ERROR] /home/at/git/spring-graphql-api/spring-graphql-api/src/test/java/com/divitngoc/controller/MusicApiControllerTest.java:[21,44] package com.divitngoc.generated.tables.pojos does not exist
[ERROR] /home/at/git/spring-graphql-api/spring-graphql-api/src/test/java/com/divitngoc/graphql/ArtistResolverTest.java:[16,44] package com.divitngoc.generated.tables.pojos does not exist
[ERROR] /home/at/git/spring-graphql-api/spring-graphql-api/src/test/java/com/divitngoc/db/service/ArtistServiceTest.java:[18,44] package com.divitngoc.generated.tables.pojos does not exist
[ERROR] /home/at/git/spring-graphql-api/spring-graphql-api/src/test/java/com/divitngoc/db/service/SongServiceTest.java:[20,44] package com.divitngoc.generated.tables.pojos does not exist
[ERROR] /home/at/git/spring-graphql-api/spring-graphql-api/src/test/java/com/divitngoc/graphql/SongResolverTest.java:[15,44] package com.divitngoc.generated.tables.pojos does not exist
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by divitngoc** [comment]
@AndreiTuta Hey can you try again, this should be fixed now.

**Comment by divitngoc** [comment]
This is now fixed.
